using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace PC4U
{
    /// <summary>
    /// This program is automatically generated by Visual Studio, and handles initalisation of the
    /// program. I have added command line arguments for enabling debugging mode as this is a full
    /// screen applcation and also can help the PC4U technicians diagnose any issues with the
    /// kisosk systems
    /// </summary>
    public partial class App : Application
    {
        void StartUp(object sender, StartupEventArgs e)
        {
            // Application is running
            // Process command line args
            bool developer = false;
            for (int i = 0; i != e.Args.Length; ++i)
            {
                if (e.Args[i] == "-debug")
                {
                    developer = true;
                }
            }

            // Create main application window, passes the developer flag onto the main window to
            // allow this to be accessed by the main program
            MainWindow mainWindow = new MainWindow(developer);
            
            // Show the main window
            mainWindow.Show();
        }
    }
}
