using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace PC4U_Admin
{
    //// <summary>
    /// This program is automatically generated by Visual Studio, and handles initalisation of the
    /// program. 
    /// </summary>
    public partial class App : Application
    {
        void StartUp(object sender, StartupEventArgs e)
        {           
            // Show the main window
            mainWindow.Show();
        }
    }
}
